site_name: ZeroNet
site_url: https://github.com/HelloZeroNet/ZeroNet
site_description: Decentralized websites using Bitcoin crypto and the BitTorrent network

repo_url: https://github.com/HelloZeroNet/ZeroNet

extra_css: [docs.css]
extra_javascript: [docs.js]


pages:
- Introduction: "index.md"
- Frequently asked questions: "faq.md"
- Start using ZeroNet:
  - "Installing": using_zeronet/installing.md
  - "Sample sites": using_zeronet/sample_sites.md
  - "Create new site": using_zeronet/create_new_site.md
- "Site Development":
  - "Getting Started": "site_development/getting_started.md"
  - "ZeroFrame API reference": "site_development/zeroframe_api_reference.md"
  - "Structure of content.json": "site_development/content_json.md"
  - "Structure of dbschema.json": "site_development/dbschema_json.md"
  - "Certificate authority": "site_development/cert_authority.md"
- "Help ZeroNet development":
  - "Contributing to ZeroNet": "help_zeronet/contributing.md"
  - "Network protocol": "help_zeronet/network_protocol.md"
  - "Donation": "help_zeronet/donate.md"

theme_dir: readthedocs
