site_name: ZeroNet
site_url: https://github.com/HelloZeroNet/ZeroNet
site_description: Decentralized websites using Bitcoin crypto and the BitTorrent network

repo_url: https://github.com/HelloZeroNet/ZeroNet
edit_uri: ../Documentation/edit/master/docs/

extra_css: [docs.css]
extra_javascript: [docs.js]
theme:
  feature:
    tabs: true
  palette:
    primary: "deep purple"
    accent: "deep purple"
  logo: "logo/zeronet_logo.svg"
  name: "readthedocs"
  favicon: "logo/favicon.ico"

markdown_extensions:
  - toc:
      permalink: true

nav:
- Introduction: "index.md"
- Frequently asked questions: "faq.md"
- Start using ZeroNet:
  - "using_zeronet/installing.md"
  - "using_zeronet/sample_sites.md"
  - "using_zeronet/create_new_site.md"
- Site Development:
  - "site_development/getting_started.md"
  - "site_development/zeroframe_api_reference.md"
  - "site_development/content_json.md"
  - "site_development/dbschema_json.md"
  - "site_development/cert_authority.md"
- Help ZeroNet development:
  - "help_zeronet/contributing.md"
  - "help_zeronet/coding_conventions.md"
  - "help_zeronet/network_protocol.md"
  - "help_zeronet/donate.md"
